FROM library/ubuntu:20.04 as UBUNTU_BASE
MAINTAINER alessandri.luca1991@gmail.com
ARG DEBIAN_FRONTEND=noninteractive
COPY p7zip_16.02 /tmp/
RUN mkdir data \
	&& cd /tmp/ && make \
	&& make all \
	&& cp ./bin/7za /bin
