install.packages('Rtsne', repos='http://cran.us.r-project.org')
install.packages('BiocManager', repos='http://cran.us.r-project.org')
BiocManager::install("GenomicRanges")
BiocManager::install(c('BiocGenerics', 'DelayedArray', 'DelayedMatrixStats',
                       'limma', 'S4Vectors', 'SingleCellExperiment',
                       'SummarizedExperiment', 'batchelor', 'Matrix.utils'))
install.packages("tidyverse",repos='http://cran.us.r-project.org')
install.packages("stringr",repos='http://cran.us.r-project.org')
install.packages("grid",repos='http://cran.us.r-project.org')
install.packages("viridis",repos='http://cran.us.r-project.org')
install.packages("ggthemes",repos='http://cran.us.r-project.org')
install.packages("dplyr",repos='http://cran.us.r-project.org')
install.packages("ggsignif",repos='http://cran.us.r-project.org')
install.packages("umap",repos='http://cran.us.r-project.org')
install.packages("heatmap3",repos='http://cran.us.r-project.org')
install.packages("plyr",repos='http://cran.us.r-project.org')
BiocManager::install("edgeR")
install.packages("dbscan",repos='http://cran.us.r-project.org')
BiocManager::install("MAST")
install.packages("geosphere",repos='http://cran.us.r-project.org')
install.packages("RColorBrewer",repos='http://cran.us.r-project.org')
install.packages("Seurat",repos='http://cran.us.r-project.org')
install.packages("htmlwidgets",repos='http://cran.us.r-project.org')
install.packages("devtools",repos='http://cran.us.r-project.org')
